tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "jaehong21/tap"
tap "jandedobbeleer/oh-my-posh"
tap "jesseduffield/lazygit"

brew "aws/tap/eks-node-viewer"
brew "jaehong21/tap/hibiscus"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jesseduffield/lazygit/lazygit"

brew "antidote"
brew "awscli"
brew "colima"
brew "dive"
brew "docker"
brew "doggo"
brew "fd"
brew "flyway"
brew "gh"
brew "git"
brew "gitui"
brew "gnupg"
brew "gradle"
brew "helm"
brew "htop"
brew "httpie"
brew "hugo"
brew "jq"
brew "k9s"
brew "krew"
brew "kubernetes-cli"
brew "lima"
brew "mas"
brew "mise"
brew "postgresql@14"
brew "pre-commit"
brew "qemu"
brew "redis"
brew "ripgrep"
brew "rye"
brew "sd"
brew "skopeo"
brew "step"
brew "terragrunt"
brew "tfenv"
brew "tree"
brew "watch"
brew "wget"
brew "yq"

cask "1password"
cask "arc"
cask "font-hack-nerd-font"
cask "hammerspoon"
cask "jetbrains-toolbox"
cask "jordanbaird-ice"
cask "linear-linear"
cask "notion"
cask "obsidian"
cask "postman"
cask "pritunl"
cask "raycast"
cask "redisinsight"
cask "scroll-reverser"
cask "setapp"

mas "Channel Talk", id: 1102655071
mas "KakaoTalk", id: 869223134
mas "Microsoft Excel", id: 462058435
mas "Microsoft Outlook", id: 985367838
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Petrify", id: 1451177988
mas "RunCat", id: 1429033973
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
